create database juegoahorcado;

create table PALABRAS(
ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
PALABRA varchar(50)
);

create table ESTADISTICAS(
ID_ESTADISTICA int NOT NULL AUTO_INCREMENT PRIMARY KEY,
FECHA datetime
);

create table DETALLEJUGADORES(
ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBREJUGADOR varchar(50),
CANTIDAD_ACIERTOS int,
CANTIDAD_ERRORES int,
GANADOR bool,
ID_ESTADISTICA int
);